-- Creación tablas
CREATE TABLE bodega (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    tamano NUMBER(5, 0) NOT NULL,
    sucursal_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE bodega ADD CONSTRAINT bodega_pk PRIMARY KEY ( id );

CREATE TABLE bodegaproducto (
    existencias NUMBER(10, 0) NOT NULL,
    preciopromedio NUMBER(10, 2) NOT NULL,
    capacidad NUMBER(10, 0) NOT NULL,
    bodega_id NUMBER(10, 0) NOT NULL,
    producto_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE bodegaproducto ADD CONSTRAINT bodegaproducto_pk PRIMARY KEY ( bodega_id, producto_id );

CREATE TABLE categoria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    descripcion VARCHAR2(510) NOT NULL,
    caracteristicas VARCHAR2(510) NOT NULL
);

ALTER TABLE categoria ADD CONSTRAINT categoria_pk PRIMARY KEY ( id );

CREATE TABLE ciudad (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL
);

ALTER TABLE ciudad ADD CONSTRAINT ciudad_pk PRIMARY KEY ( id );

CREATE TABLE ordencompra (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fechacreacion DATE NOT NULL,
    fechaentrega DATE NOT NULL,
    fecharecepcion DATE,
    estado VARCHAR2(50) NOT NULL,
    proveedor_id NUMBER(10, 0) NOT NULL,
    sucursal_id NUMBER(10, 0) NOT NULL,
    bodega_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_pk PRIMARY KEY ( id );

CREATE TABLE ordenproducto (
    cantidad NUMBER(10, 0) NOT NULL,
    precio NUMBER(10, 2) NOT NULL,
    ordencompra_id NUMBER(10, 0) NOT NULL,
    producto_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE ordenproducto ADD CONSTRAINT ordenproducto_pk PRIMARY KEY ( ordencompra_id, producto_id );

CREATE TABLE producto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    costobodega NUMBER(10, 2) NOT NULL,
    preciounitario NUMBER(10, 2) NOT NULL,
    presentacion VARCHAR2(255) NOT NULL,
    cantidad NUMBER(10, 0) NOT NULL,
    unidadmedida VARCHAR2(50) NOT NULL,
    volumenempaque NUMBER(10, 2) NOT NULL,
    pesoempaque NUMBER(10, 2) NOT NULL,
    fechaexpiracion DATE,
    codigobarras VARCHAR2(50) NOT NULL,
    categoria_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE producto ADD CONSTRAINT producto_pk PRIMARY KEY ( id );

CREATE TABLE productosucursal (
    cantidadminima NUMBER(10, 0) NOT NULL,
    sucursal_id NUMBER(10, 0) NOT NULL,
    producto_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE productosucursal ADD CONSTRAINT productosucursal_pk PRIMARY KEY ( sucursal_id, producto_id );

CREATE TABLE proveedor (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nit NUMBER(10, 0) NOT NULL,
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    nombrecontacto VARCHAR2(255) NOT NULL,
    telefonocontacto NUMBER(15, 0) NOT NULL
);

ALTER TABLE proveedor ADD CONSTRAINT proveedor_pk PRIMARY KEY ( id );

CREATE TABLE proveedorproducto (
    producto_id NUMBER(10, 0) NOT NULL,
    proveedor_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE proveedorproducto ADD CONSTRAINT proveedorproducto_pk PRIMARY KEY ( producto_id, proveedor_id );

CREATE TABLE proveedorsucursal (
    sucursal_id NUMBER(10, 0) NOT NULL,
    proveedor_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE proveedorsucursal ADD CONSTRAINT proveedorsucursal_pk PRIMARY KEY ( sucursal_id, proveedor_id );

CREATE TABLE sucursal (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    telefono NUMBER(15, 0) NOT NULL,
    tamano NUMBER(5, 0) NOT NULL,
    ciudad_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE sucursal ADD CONSTRAINT sucursal_pk PRIMARY KEY ( id );

-- Relacionando las tablas
ALTER TABLE bodega ADD CONSTRAINT bodega_sucursal_fk FOREIGN KEY (sucursal_id) REFERENCES sucursal (id) ON DELETE CASCADE;
ALTER TABLE bodegaproducto ADD CONSTRAINT bodegaproducto_bodega_fk FOREIGN KEY (bodega_id) REFERENCES bodega (id) ON DELETE CASCADE;
ALTER TABLE bodegaproducto ADD CONSTRAINT bodegaproducto_producto_fk FOREIGN KEY (producto_id) REFERENCES producto (id) ON DELETE CASCADE;
ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_bodega_fk FOREIGN KEY (bodega_id) REFERENCES bodega (id) ON DELETE CASCADE;
ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_proveedor_fk FOREIGN KEY (proveedor_id) REFERENCES proveedor (id) ON DELETE CASCADE;
ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_sucursal_fk FOREIGN KEY (sucursal_id) REFERENCES sucursal (id) ON DELETE CASCADE;
ALTER TABLE ordenproducto ADD CONSTRAINT ordenproducto_ordencompra_fk FOREIGN KEY (ordencompra_id) REFERENCES ordencompra (id) ON DELETE CASCADE;
ALTER TABLE ordenproducto ADD CONSTRAINT ordenproducto_producto_fk FOREIGN KEY (producto_id) REFERENCES producto (id) ON DELETE CASCADE;
ALTER TABLE producto ADD CONSTRAINT producto_categoria_fk FOREIGN KEY (categoria_id) REFERENCES categoria (id) ON DELETE CASCADE;
ALTER TABLE productosucursal ADD CONSTRAINT productosucursal_producto_fk FOREIGN KEY (producto_id) REFERENCES producto (id) ON DELETE CASCADE;
ALTER TABLE productosucursal ADD CONSTRAINT productosucursal_sucursal_fk FOREIGN KEY (sucursal_id) REFERENCES sucursal (id) ON DELETE CASCADE;
ALTER TABLE proveedorproducto ADD CONSTRAINT proveedorproducto_producto_fk FOREIGN KEY (producto_id) REFERENCES producto (id) ON DELETE CASCADE;
ALTER TABLE proveedorproducto ADD CONSTRAINT proveedorproducto_proveedor_fk FOREIGN KEY (proveedor_id) REFERENCES proveedor (id) ON DELETE CASCADE;
ALTER TABLE proveedorsucursal ADD CONSTRAINT proveedorsucursal_proveedor_fk FOREIGN KEY (proveedor_id) REFERENCES proveedor (id) ON DELETE CASCADE;
ALTER TABLE proveedorsucursal ADD CONSTRAINT proveedorsucursal_sucursal_fk FOREIGN KEY (sucursal_id) REFERENCES sucursal (id) ON DELETE CASCADE;
ALTER TABLE sucursal ADD CONSTRAINT sucursal_ciudad_fk FOREIGN KEY (ciudad_id) REFERENCES ciudad (id) ON DELETE CASCADE;


-- Restricciones de las tablas
-- Unique
ALTER TABLE categoria ADD CONSTRAINT unique_categoria_nombre UNIQUE (nombre);
ALTER TABLE ciudad ADD CONSTRAINT unique_ciudad_nombre UNIQUE (nombre);
ALTER TABLE producto ADD CONSTRAINT unique_producto_nombre UNIQUE (nombre);
ALTER TABLE producto ADD CONSTRAINT unique_producto_codigobarras UNIQUE (codigobarras);
ALTER TABLE proveedor ADD CONSTRAINT unique_proveedor_nit UNIQUE (nit);
ALTER TABLE proveedor ADD CONSTRAINT unique_proveedor_nombre UNIQUE (nombre);
ALTER TABLE proveedor ADD CONSTRAINT unique_proveedor_telefonocontacto UNIQUE (telefonocontacto);
ALTER TABLE sucursal ADD CONSTRAINT unique_sucursal_telefono UNIQUE (telefono);
ALTER TABLE ordencompra ADD CONSTRAINT unique_ordencompra UNIQUE (fechacreacion, fechaentrega, proveedor_id, sucursal_id, bodega_id);
ALTER TABLE bodega ADD CONSTRAINT unique_bodega_nombre_sucursal UNIQUE (nombre, sucursal_id);
ALTER TABLE sucursal ADD CONSTRAINT unique_sucursal_nombre_ciudad UNIQUE (nombre, ciudad_id);

-- Población de tabla categoría
INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Perecederos', 'Perecederos, tienen fecha de vencimiento', 'Almacenamiento en frío, con fecha de caducidad');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('No perecederos', 'No perecederos, sin fecha de vencimiento cercana', 'Almacenamiento en lugar seco y fresco');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Aseo', 'Productos de limpieza y aseo', 'Almacenamiento en lugares ventilados y seguros');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Congelados', 'Alimentos y productos congelados', 'Almacenamiento en congeladores a temperaturas bajo cero');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Prendas de vestir', 'Ropa y prendas de uso personal', 'Almacenamiento en estantes y perchas');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Muebles', 'Mobiliario para el hogar u oficina', 'Almacenamiento en lugares amplios, evitar humedad');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Herramientas', 'Herramientas de trabajo y uso doméstico', 'Almacenamiento en cajas de herramientas, lugares secos');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Electrodomésticos', 'Aparatos eléctricos para uso doméstico', 'Almacenamiento en lugares seguros, evitar golpes');

-- Población de tabla productos
-- Población tabla producto de productos perecederos
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Papas fritas Les frites', 4200, 9000, 'Paquetón de 5 paquetes de 200 gr.', 1000, 'gr', 150, 15, TO_DATE('12/12/2027', 'DD/MM/YYYY'), 'f0f0f0f0f0', 1);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Leche Deslactosada Alpina', 2000, 3000, 'Caja de 6 botellas de 1 litro', 6000, 'ml', 1000, 50, TO_DATE('01/01/2025', 'DD/MM/YYYY'), 'a1a1a1a1a1', 1);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Queso Mozzarella La Quesera', 8500, 15000, 'Bloque de 500 gr.', 500, 'gr', 200, 30, TO_DATE('30/09/2026', 'DD/MM/YYYY'), 'b2b2b2b2b2', 1);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Yogurt Natural Alpina', 1800, 2500, 'Paquete de 6 botellas de 250 ml', 1500, 'ml', 120, 20, TO_DATE('15/06/2026', 'DD/MM/YYYY'), 'c3c3c3c3c3', 1);

-- Población tabla producto de productos no perecederos
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Atún en lata Van Camps', 3000, 5500, 'Caja de 6 latas de 150 gr.', 900, 'gr', 100, 25, NULL, 'd4d4d4d4d4', 2);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Frijoles enlatados La Roca', 1500, 3000, 'Lata de 500 gr.', 500, 'gr', 120, 40, NULL, 'e5e5e5e5e5', 2);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Arroz Blanco Diana', 4500, 9000, 'Bolsa de 1 Kg.', 1000, 'gr', 200, 20, NULL, 'f6f6f6f6f6', 2);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Galletas Saltín Noel', 2200, 4000, 'Paquete de 12 galletas', 500, 'gr', 150, 10, NULL, 'g7g7g7g7g7', 2);

-- Población tabla producto de productos de aseo
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Detergente en polvo Ariel', 5000, 10000, 'Bolsa de 2 Kg.', 2000, 'gr', 500, 50, NULL, 'h8h8h8h8h8', 3);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Jabón Líquido Protex', 1200, 2400, 'Botella de 500 ml.', 500, 'ml', 100, 20, NULL, 'i9i9i9i9i9', 3);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Desinfectante Lysol', 6000, 12000, 'Spray de 1 litro', 1000, 'ml', 200, 60, NULL, 'j0j0j0j0j0', 3);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Cloro Blanquita', 8000, 16000, 'Botella de 2 litros', 2000, 'ml', 300, 100, NULL, 'k1k1k1k1k1', 3);

-- Población tabla producto de productos congelados
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Helado de Vainilla Popsy', 5000, 9000, 'Caja de 1 litro', 1000, 'ml', 300, 500, NULL, 'l2l2l2l2l2', 4);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Nuggets de Pollo McCain', 7000, 14000, 'Paquete de 1 Kg.', 1000, 'gr', 400, 600, NULL, 'm3m3m3m3m3', 4);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Pizza Congelada Ristorante', 4500, 9000, 'Paquete de 500 gr.', 500, 'gr', 200, 150, NULL, 'n4n4n4n4n4', 4);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Papas Fritas McCain', 3500, 7000, 'Paquete de 1 Kg.', 1000, 'gr', 300, 250, NULL, 'o5o5o5o5o5', 4);

-- Población tabla producto de prendas de vestir
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Camisa de Algodón', 100000, 250000, 'Paquete de 1 unidad', 500, 'gr', 200, 100, NULL, 'p6p6p6p6p6', 5);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Pantalón Jeans', 150000, 400000, 'Paquete de 1 unidad', 700, 'gr', 300, 200, NULL, 'q7q7q7q7q7', 5);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Camiseta Deportiva', 50000, 150000, 'Paquete de 1 unidad', 300, 'gr', 100, 80, NULL, 'r8r8r8r8r8', 5);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Chaqueta de Cuero', 300000, 600000, 'Paquete de 1 unidad', 1200, 'gr', 500, 300, NULL, 's9s9s9s9s9', 5);

-- Población tabla producto de muebles
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Silla de Oficina', 500000, 1000000, 'Paquete de 1 unidad', 10000, 'gr', 5000, 3000, NULL, 't1t1t1t1t1', 6);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Mesa de Centro', 700000, 1500000, 'Paquete de 1 unidad', 15000, 'gr', 8000, 4000, NULL, 'u2u2u2u2u2', 6);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Sofá de 3 Plazas', 1200000, 3000000, 'Paquete de 1 unidad', 40000, 'gr', 20000, 10000, NULL, 'v3v3v3v3v3', 6);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Estante de Madera', 400000, 800000, 'Paquete de 1 unidad', 25000, 'gr', 15000, 6000, NULL, 'w4w4w4w4w4', 6);

-- Población tabla producto de herramientas
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Martillo', 50000, 100000, 'Paquete de 1 unidad', 500, 'gr', 300, 200, NULL, 'x5x5x5x5x5', 7);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Destornillador', 30000, 80000, 'Paquete de 1 unidad', 200, 'gr', 100, 80, NULL, 'y6y6y6y6y6', 7);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Llave Inglesa', 80000, 150000, 'Paquete de 1 unidad', 700, 'gr', 400, 300, NULL, 'z7z7z7z7z7', 7);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Taladro Eléctrico', 250000, 500000, 'Paquete de 1 unidad', 2000, 'gr', 1500, 1200, NULL, 'a8a8a8a8a8', 7);

-- Población tabla producto de electrodomésticos
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Televisor 42 pulgadas', 3000000, 6000000, 'Paquete de 1 unidad', 20000, 'gr', 5000, 3000, NULL, 'b9b9b9b9b9', 8);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Nevera No Frost', 5000000, 10000000, 'Paquete de 1 unidad', 40000, 'gr', 10000, 6000, NULL, 'c0c0c0c0c0', 8);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Microondas', 800000, 1500000, 'Paquete de 1 unidad', 10000, 'gr', 3000, 1500, NULL, 'd1d1d1d1d1', 8);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Aspiradora', 900000, 1800000, 'Paquete de 1 unidad', 15000, 'gr', 4000, 2500, NULL, 'e2e2e2e2e2', 8);

-- Población tabla ciudad
INSERT INTO ciudad (nombre) 
VALUES ('Bucaramanga');

INSERT INTO ciudad (nombre) 
VALUES ('Bogotá');

-- Población tabla sucursal
-- Población tabla sucursal en Bucaramanga
INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Norte', 'Calle 1 #2-3', 6014563399, 1200, (SELECT id FROM ciudad WHERE nombre = 'Bucaramanga'));

INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Sur', 'Calle 4 #5-6', 6017654321, 800, (SELECT id FROM ciudad WHERE nombre = 'Bucaramanga'));

-- Población tabla sucursal en Bogotá
INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Occidente', 'Carrera 7 #8-9', 6011112222, 1500, (SELECT id FROM ciudad WHERE nombre = 'Bogotá'));

INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Oriente', 'Carrera 10 #11-12', 6013334444, 1000, (SELECT id FROM ciudad WHERE nombre = 'Bogotá'));

-- Población tabla bodega
-- Población tabla bodega para las sucursales de Bucaramanga
INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Cabecera del Llano', 500, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Norte'));

INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Real de Minas', 300, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Sur'));

-- Población tabla bodega para las sucursales de Bogotá
INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Portal 80', 700, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Occidente'));

INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Usme', 450, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Oriente'));

-- Población tabla proveedor
INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9001234567, 'Proveedor de Alimentos S.A.', 'Carrera 15 #45-67, Bogotá', 'Carlos Ramírez', 3111234567);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9007654321, 'Distribuidora de Aseo Ltda.', 'Avenida 68 #22-55, Bogotá', 'Laura Gómez', 3207654321);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9004567890, 'Comercializadora Congelados S.A.S.', 'Calle 100 #15-75, Bogotá', 'Juan Pérez', 3004567890);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9009876543, 'Muebles y Estilos S.A.S.', 'Calle 80 #20-30, Bogotá', 'Sandra Rodríguez', 3109876543);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9006543210, 'Electrodomésticos del Hogar Ltda.', 'Carrera 30 #75-10, Bogotá', 'Jorge Martínez', 3016543210);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9004567388, 'Proveedor de Ropa S.A.', 'Carrera 10 #20-30, Bogotá', 'Ana María López', 3201234567);

-- Población proveedorproducto
-- Población tabla proveedorproducto para Proveedor de Alimentos S.A.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Papas fritas Les frites'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Leche Deslactosada Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Queso Mozzarella La Quesera'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Yogurt Natural Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Atún en lata Van Camps'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Frijoles enlatados La Roca'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Arroz Blanco Diana'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Galletas Saltín Noel'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

-- Población tabla proveedorproducto para Comercializadora Congelados S.A.S.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Helado de Vainilla Popsy'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Nuggets de Pollo McCain'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Pizza Congelada Ristorante'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Papas Fritas McCain'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Queso Mozzarella La Quesera'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Yogurt Natural Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Leche Deslactosada Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Frijoles enlatados La Roca'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

-- Población tabla proveedorproducto para Distribuidora de Aseo Ltda.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Detergente en polvo Ariel'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Jabón Líquido Protex'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Desinfectante Lysol'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Cloro Blanquita'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

-- Población tabla proveedorproducto para Proveedor de Ropa S.A.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Camisa de Algodón'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Pantalón Jeans'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Camiseta Deportiva'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Chaqueta de Cuero'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.'));

-- Población tabla proveedorproducto para Muebles y Estilos S.A.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Silla de Oficina'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Mesa de Centro'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Sofá de 3 Plazas'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Estante de Madera'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Martillo'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Destornillador'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Llave Inglesa'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Taladro Eléctrico'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.'));

-- Población tabla proveedorproducto para Electrodomésticos del Hogar Ltda.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Televisor 42 pulgadas'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Nevera No Frost'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Microondas'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Aspiradora'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Silla de Oficina'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Mesa de Centro'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Sofá de 3 Plazas'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Estante de Madera'), (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.'));

-- Población tabla proveedorsucursal
INSERT INTO proveedorsucursal (sucursal_id, proveedor_id)
SELECT sucursal.id, proveedor.id FROM sucursal, proveedor;

-- Población tabla productosucursal para todas las sucursales
-- Sucursal Norte 
INSERT INTO productosucursal (sucursal_id, producto_id, cantidadminima)
SELECT (SELECT id FROM sucursal WHERE nombre = 'Sucursal Norte'), id, 
  CASE 
    WHEN categoria_id = 1 THEN 500  
    WHEN categoria_id = 2 THEN 400  
    WHEN categoria_id = 3 THEN 300  
    WHEN categoria_id = 4 THEN 200  
    WHEN categoria_id = 5 THEN 150  
    WHEN categoria_id = 6 THEN 100  
    WHEN categoria_id = 7 THEN 80   
    WHEN categoria_id = 8 THEN 70   
  END 
FROM producto;

-- Sucursal Sur
INSERT INTO productosucursal (sucursal_id, producto_id, cantidadminima)
SELECT (SELECT id FROM sucursal WHERE nombre = 'Sucursal Sur'), id, 
  CASE 
    WHEN categoria_id = 1 THEN 400 
    WHEN categoria_id = 2 THEN 350  
    WHEN categoria_id = 3 THEN 250  
    WHEN categoria_id = 4 THEN 150  
    WHEN categoria_id = 5 THEN 100  
    WHEN categoria_id = 6 THEN 75   
    WHEN categoria_id = 7 THEN 60   
    WHEN categoria_id = 8 THEN 50   
  END 
FROM producto;

-- Sucursal Occidente 
INSERT INTO productosucursal (sucursal_id, producto_id, cantidadminima)
SELECT (SELECT id FROM sucursal WHERE nombre = 'Sucursal Occidente'), id, 
  CASE 
    WHEN categoria_id = 1 THEN 600  
    WHEN categoria_id = 2 THEN 500  
    WHEN categoria_id = 3 THEN 400  
    WHEN categoria_id = 4 THEN 300  
    WHEN categoria_id = 5 THEN 200  
    WHEN categoria_id = 6 THEN 150  
    WHEN categoria_id = 7 THEN 120  
    WHEN categoria_id = 8 THEN 100  
  END 
FROM producto;

-- Sucursal Oriente 
INSERT INTO productosucursal (sucursal_id, producto_id, cantidadminima)
SELECT (SELECT id FROM sucursal WHERE nombre = 'Sucursal Oriente'), id, 
  CASE 
    WHEN categoria_id = 1 THEN 300  
    WHEN categoria_id = 2 THEN 250  
    WHEN categoria_id = 3 THEN 200  
    WHEN categoria_id = 4 THEN 150  
    WHEN categoria_id = 5 THEN 100  
    WHEN categoria_id = 6 THEN 70   
    WHEN categoria_id = 7 THEN 50   
    WHEN categoria_id = 8 THEN 40  
  END 
FROM producto;

-- Poblacion tabla ordencompra
-- Bodega Cabecera del Llano (Sucursal Norte)
INSERT INTO ordencompra (fechacreacion, fechaentrega, estado, proveedor_id, sucursal_id, bodega_id)
SELECT TRUNC(SYSDATE), TRUNC(SYSDATE + 15), 'Vigente', p.id, 
       (SELECT id FROM sucursal WHERE nombre = 'Sucursal Norte'), 
       (SELECT id FROM bodega WHERE nombre = 'Bodega Cabecera del Llano')
FROM proveedor p;

-- Bodega Real de Minas (Sucursal Sur)
INSERT INTO ordencompra (fechacreacion, fechaentrega, estado, proveedor_id, sucursal_id, bodega_id)
SELECT TRUNC(SYSDATE), TRUNC(SYSDATE + 20), 'Vigente', p.id, 
       (SELECT id FROM sucursal WHERE nombre = 'Sucursal Sur'), 
       (SELECT id FROM bodega WHERE nombre = 'Bodega Real de Minas')
FROM proveedor p;

-- Bodega Portal 80 (Sucursal Occidente)
INSERT INTO ordencompra (fechacreacion, fechaentrega, estado, proveedor_id, sucursal_id, bodega_id)
SELECT TRUNC(SYSDATE), TRUNC(SYSDATE + 25), 'Vigente', p.id, 
       (SELECT id FROM sucursal WHERE nombre = 'Sucursal Occidente'), 
       (SELECT id FROM bodega WHERE nombre = 'Bodega Portal 80')
FROM proveedor p;

-- Bodega Usme (Sucursal Oriente)
INSERT INTO ordencompra (fechacreacion, fechaentrega, estado, proveedor_id, sucursal_id, bodega_id)
SELECT TRUNC(SYSDATE), TRUNC(SYSDATE + 30), 'Vigente', p.id, 
       (SELECT id FROM sucursal WHERE nombre = 'Sucursal Oriente'), 
       (SELECT id FROM bodega WHERE nombre = 'Bodega Usme')
FROM proveedor p;

-- Población tabla ordenproducto
-- Proveedor de Alimentos S.A.
INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 200, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Papas fritas Les frites'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 300, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Leche Deslactosada Alpina'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 240, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Queso Mozzarella La Quesera'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 200, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Yogurt Natural Alpina'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 160, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Atún en lata Van Camps'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 100, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Frijoles enlatados La Roca'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 240, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Arroz Blanco Diana'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 300, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Galletas Saltín Noel'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.');

-- Comercializadora Congelados S.A.S.
INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 300, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Leche Deslactosada Alpina'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 240, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Queso Mozzarella La Quesera'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 200, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Yogurt Natural Alpina'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 300, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Frijoles enlatados La Roca'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 240, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Helado de Vainilla Popsy'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 200, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Nuggets de Pollo McCain'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 240, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Pizza Congelada Ristorante'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 280, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Papas Fritas McCain'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.');


-- Distribuidora de Aseo Ltda.
INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 300, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Detergente en polvo Ariel'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 400, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Jabón Líquido Protex'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 240, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Desinfectante Lysol'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 200, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Cloro Blanquita'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.');

-- Proveedor de Ropa S.A.
INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 150, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Camisa de Algodón'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 120, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Pantalón Jeans'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 240, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Camiseta Deportiva'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 200, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Chaqueta de Cuero'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.');

-- Muebles y Estilos S.A.S.
INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 40, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Silla de Oficina'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 20, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Mesa de Centro'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 10, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Sofá de 3 Plazas'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 16, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Estante de Madera'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 100, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Martillo'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 80, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Destornillador'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 60, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Llave Inglesa'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 40, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Taladro Eléctrico'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S.');

-- Electrodomésticos del Hogar Ltda.
INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 200, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Silla de Oficina'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 60, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Mesa de Centro'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 40, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Sofá de 3 Plazas'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 30, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Estante de Madera'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 100, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Televisor 42 pulgadas'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 50, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Nevera No Frost'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 40, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Microondas'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

INSERT INTO ordenproducto (ordencompra_id, producto_id, cantidad, precio)
SELECT oc.id, p.id, 60, p.preciounitario
FROM ordencompra oc
JOIN producto p ON p.nombre = 'Aspiradora'
WHERE oc.proveedor_id = (SELECT id FROM proveedor WHERE nombre = 'Electrodomésticos del Hogar Ltda.');

-- Población tabla bodegaproducto
INSERT INTO bodegaproducto (bodega_id, producto_id, existencias, preciopromedio, capacidad)
SELECT b.id, p.id, 0, 0, 20000
FROM bodega b, producto p;

COMMIT;